<a href="https://colab.research.google.com/github/saqqad00-pixel/python-learning-journey/blob/main/saad_lec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [19]:
data=pd.read_csv("/content/data - Sheet1 (2).csv")
data

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no
7,8886,Bachelors,2016,Aqaba,34,Female,550.0,2.0,no
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no
13,1056,Bachelors,2016,Aqaba,39,Male,560.0,2.0,no
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no

In [3]:
data.shape

(22, 10)

In [20]:
data.dtypes

id               int64
Education       object
JoiningYear      int64
City            object
Age              int64
Gender          object
salary         float64
Experience     float64
LeaveOrNot      object
dtype: object

In [30]:
data.empty

False

In [22]:
data.head(3)

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no

In [23]:
data.head(19)

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no
7,8886,Bachelors,2016,Aqaba,34,Female,550.0,2.0,no
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no
13,1056,Bachelors,2016,Aqaba,39,Male,560.0,2.0,no
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no

In [24]:
data.head(1)

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes

In [25]:
data['City']

0     Amman
1     Irbid
2     Irbid
3     Irbid
4     Amman
5     Amman
6     Irbid
7     Aqaba
8     Amman
9     Amman
10    Amman
11    Amman
12    Irbid
13    Aqaba
14    Irbid
15    Irbid
16    Amman
17    Amman
18    Amman
19    Amman
20    Amman
21    Amman
Name: City, dtype: object

In [26]:
data['Age']

0     34
1     28
2     38
3     27
4     24
5     22
6     38
7     34
8     23
9     37
10    27
11    34
12    32
13    39
14    37
15    29
16    34
17    34
18    30
19    30
20    30
21    30
Name: Age, dtype: int64

In [29]:
data[data["City"]=="Irbid"]

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no

In [31]:
data.isnull().sum()

id             0
Education      0
JoiningYear    0
City           0
Age            0
Gender         0
salary         1
Experience     1
LeaveOrNot     1
dtype: int64

In [35]:
data.isnull().sum().sum()

np.int64(3)

In [33]:
data['new_column']=6
data

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot,new_column
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes,6
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no,6
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no,6
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN,6
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes,6
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes,6
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no,6
7,8886,Bachelors,2016,Aqaba,34,Female,550.0,2.0,no,6
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no,6
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no,6
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no,6
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no,6
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no,6
13,1056,Bachelors,2016,Aqaba,39,Male,560.0,2.0,no,6
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes,6
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no,6
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no,6
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no,6
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no,6
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no,6
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no,6
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no,6

In [37]:
data['new_salary']=data['salary']+50
data

,id,Education,JoiningYear,City,Age,Gender,salary,Experience,LeaveOrNot,new_column,new_salary
0,8675,Bachelors,2017,Amman,34,Male,500.0,0.0,yes,6,550.0
1,1531,Bachelors,2013,Irbid,28,Female,560.0,3.0,no,6,610.0
2,3028,PHD,2014,Irbid,38,Female,1000.0,2.0,no,6,1050.0
3,2203,Masters,2016,Irbid,27,Female,800.0,5.0,NaN,6,850.0
4,4848,Masters,2017,Amman,24,Male,800.0,2.0,yes,6,850.0
5,6877,Bachelors,2016,Amman,22,Male,550.0,0.0,yes,6,600.0
6,2012,Bachelors,2015,Irbid,38,Male,550.0,0.0,no,6,600.0
7,8886,Bachelors,2016,Aqaba,34,Female,550.0,2.0,no,6,600.0
8,8741,Bachelors,2016,Amman,23,Male,550.0,1.0,no,6,600.0
9,6789,Masters,2017,Amman,37,Male,900.0,2.0,no,6,950.0
10,9872,Masters,2012,Amman,27,Male,800.0,5.0,no,6,850.0
11,2017,Bachelors,2016,Amman,34,Male,700.0,3.0,no,6,750.0
12,3018,PHD,2018,Irbid,32,Male,1500.0,5.0,no,6,1550.0
13,1056,Bachelors,2016,Aqaba,39,Male,560.0,2.0,no,6,610.0
14,6845,Bachelors,2012,Irbid,37,Male,NaN,NaN,yes,6,NaN
15,4245,Bachelors,2017,Irbid,29,Female,500.0,3.0,no,6,550.0
16,6688,Bachelors,2014,Amman,34,Female,550.0,2.0,no,6,600.0
17,9764,Bachelors,2014,Amman,34,Male,600.0,4.0,no,6,650.0
18,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no,6,700.0
19,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no,6,700.0
20,2099,Bachelors,2015,Amman,30,Female,650.0,0.0,no,6,700.0
21,3001,Bachelors,2010,Amman,30,Male,650.0,0.0,no,6,700.0